name: regression-mlpos-dvc
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc repro
          
          git fetch --prune
          
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          dvc metrics diff --show-md master > report.md
          cml comment create report.md
          cml-send-comment report.md
